server:
    port: 80
#eureka
#Eureka 配置
eureka:
    client:
        register-with-eureka: false #是否向eureka注册自己
        service-url: #监控页面
            #单机：defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
            defaultZone: http://eureka-7001.com:7001/eureka/,http://eureka-7002.com:7002/eureka/,http://eureka-7003.com:7003/eureka/
