server:
    port: 7001
#Eureka 配置
eureka:
    instance:
        hostname: eureka-7001.com
    client:
        register-with-eureka: false #是否向eureka注册自己
        fetch-registry: false #如果是false表示自己为注册中心
        service-url: #监控页面
        #单机：defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
            defaultZone: http://eureka-7002.com:7002/eureka/,http://eureka-7003.com:7003/eureka/