server:
    port: 8001
mybatis:
    type-aliases-package: api.pojo
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  application:
    name: springcloud-provider-dept
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://81.68.92.240:3306/springcloud_01?useUnicode=true&characterEncoding=utf-8
     username: root
     password: 314159