server:
    port: 8003
mybatis:
    type-aliases-package: api.pojo
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  application:
    name: springcloud-provider-dept
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://81.68.92.240:3306/springcloud_03?useUnicode=true&characterEncoding=utf-8
     username: root
     password: 314159
#eureka配置，服务注册到哪里
eureka:
    client:
      service-url:
          #发布到集群
          defaultZone: http://eureka-7001.com:7001/eureka/,http://eureka-7002.com:7002/eureka/,http://eureka-7003.com:7003/eureka/
    instance:
        instance-id: springcloud-provider-dept-8003 #修改eureka上的默认ID
# info 配置
info:
    app.name: name test
    company.name: companyname
